apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: psylance/myapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
