apiVersion: v1
kind: Service
metadata:
  name: slb-flask-app
  labels:
    app: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
